# Use an official TensorFlow image that supports multi-architecture
FROM tensorflow/tensorflow:2.12.0

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    build-essential \
    curl \
    pkg-config \
    libhdf5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip3 install --upgrade pip

# Install additional Python dependencies
RUN pip3 install fastapi uvicorn tqdm Pillow nibabel matplotlib

# Set the working directory
WORKDIR /app

# Copy application code to the container
###COPY ./app /app
COPY ./app /app/app

# Default command to run when starting the container
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
