# Stage 1: Build stage
FROM tensorflow/tensorflow:2.12.0-gpu AS builder

# Install additional dependencies for your model if needed
RUN apt-get update && apt-get install -y \
    # Additional dependencies here, if any \
    && rm -rf /var/lib/apt/lists/*

# Stage 2: Production stage
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Copy requirements and install them
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copy your app code
COPY ./app /app/app

# Copy the model if needed
#COPY --from=builder /path/to/your/model /app/model

# Set any environment variables if needed
# ENV VARIABLE_NAME=value

# Expose the port
EXPOSE 80

# Specify the startup command
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
